Public Admin vehicle AD pair | latest deployment
DIMO-Network/dimo-identity pull request #77
Opened 2023-08-11 15:52 UTC by LorranSutter

2023-08-14 14:33 UTC, elffjs commented on contracts/dev/DevAdmin.sol
> +    event AftermarketDevicePaired(
I see, just repeating.

Again, we'd like to upgrade this to a real thing at some point but this seems fine for now.

2023-08-14 14:35 UTC, elffjs requested changes
Minor things.

2023-08-14 15:36 UTC, LorranSutter commented on contracts/dev/DevAdmin.sol
> +        if (owner != INFT(adIdProxyAddress).ownerOf(aftermarketDeviceNode))
True

2023-08-15 19:53 UTC, elffjs approved these changes

2023-08-17 18:13 UTC, merged