Feature/si 2114 manufacturer table mint convenience function
DIMO-Network/dimo-identity pull request #94
Opened 2023-10-24 04:24 UTC by LorranSutter

2023-10-25 20:22 UTC, elffjs requested changes
Minor thing.

2023-10-25 20:22 UTC, elffjs commented on contracts/implementations/tableland/DeviceDefinitionTable.sol
> +            storage vs = DeviceDefinitionTableStorage.getStorage();
`vs` feels like "vehicle storage".

2023-10-26 03:30 UTC, LorranSutter commented on contracts/implementations/tableland/DeviceDefinitionTable.sol
> +            storage vs = DeviceDefinitionTableStorage.getStorage();
ops

2023-10-30 14:13 UTC, elffjs approved these changes

2023-10-30 14:17 UTC, merged